with source as (
  select * from ${ref("tasks")}
),
renamed as (
  select
    -- keys
    id :: TEXT as task_id,
    assigneeid :: TEXT as user_id,
    projectid :: TEXT as project_id,

    -- details
    name :: TEXT as task_name,
    duration :: TEXT as duration,
    estimate :: TEXT as estimate,
    status :: TEXT as status,

    -- metadata
    _sdc_batched_at::TIMESTAMP as loaded_at
  
  from source
)
select * from renamed